### ISSUE TITLE
SOCKS5 does not actually work?

### ISSUE THREAD

**Issue by E100Beta** [athos-ribeiro/noturno#11]
Choosing SOCKS5 protocol in noturno does not have any effect. HTTP(S)/SOCKS4 proxies work as intended.

Looking at debugging output in about:debugging, output looks like this:
```
Proxy off                                                          background.js:101:3
Setting proxy to SOCKS5 127.0.0.1:9050                             background.js:101:3
Proxy error: FindProxyForURL: Unrecognized proxy type: "socks5"    background.js:7:3
```
The last line loops eternally.

There is also this bit:
```
TypeError: this.transport is null                                  main.js:1521:5
```

I have Firefox 55.

**Comment by athos-ribeiro** [comment]
Thanks for the report! This bug reinforces the need to re-write a test suite, as mentioned in #3 

There is actually a problem with either the API documentation [1] or with its implementation [2]. The first says that to use SOCKS5 in newer versions of Firefox, one should use the `SOCKS5` string in the PAC file. The latter shows that `SOCKS`is the correct string that maps to SOCKS5 and that there is no mapping for a `SOCKS5` string.

I am fixing this issue and preparing a new release, and I will also open a bug upstream (Firefox) at some point.

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file#Return_value_format
[2] https://hg.mozilla.org/mozilla-central/file/tip/toolkit/components/extensions/ProxyScriptContext.jsm#l46

**Comment by athos-ribeiro** [comment]
Reported upstream @ https://bugzilla.mozilla.org/show_bug.cgi?id=1400957

**Comment by E100Beta** [comment]
You may be the quickest-reacting developer I've encountered in my life O_o
Huge thanks for what you're doing, both adding SOCKS5 and fixing it on such a short notice!

**Comment by athos-ribeiro** [comment]
@arthurmde helped tackling this one :)

Thanks for helping us improve noturno! If you believe it lacks anything or if you find any other bugs, do not hesitate contacting us!
