### ISSUE TITLE
Support one click toggle

### ISSUE THREAD

**Issue by athos-ribeiro** [athos-ribeiro/noturno#12]
According to one of our reviews on our mozilla addon page [1], users would like to toggle proxy configurations with a single click. This was the default `noturno < 1.0.0` behaviour.

The problem here is that implementing this would require substantial changes in noturno (again), since we cannot go back to using the browser's proxy settings due to the new WebextEnsions proxy API [2].

What we could easily implement without changing the default behaviour is a `advanced options` button in our current BrowserAction, which would take the user to the addon options page [3]. In this options page the user would be able to set addon configurations, such as

* Proxy configurations
* Set the hotkey to be used by noturno
* **Enable one click toggle**, which would disable the BrowserAction popup and make the button just toggle the proxy configurations using whatever proxy configurations the user had set there. To disable the **one click toggle** feature, the user would have to go a long way through the about:addon page to access noturno's options and disable it. In this case, some help text (and maybe a confirmation button) would be nice to have as well.

I would like to hear some users on this feature before going ahead and implementing this feature, so I will leave a `question` label on the issue and hopefully we will get some feedback before moving on (I also replied the user review with a link to this issue).

[1] https://addons.mozilla.org/en-US/firefox/addon/noturno/reviews/926333/
[2] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy
[3] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Options_pages

**Comment by cb88** [comment]
I figured you would leave the settings button as it is, isn't it possible to add multiple buttons in a webextension? 

Then I would just put the normal noturno button in my tools menu.

In short you'd just need to add a single button that does nothing but turn the proxy on and off and leave the rest of noturno the same.

**Comment by athos-ribeiro** [comment]
> isn't it possible to add multiple buttons in a webextension?

As per [1], an _extension can have only one browser action._ A browser action is the button we currently use.

What we can do is to have multiple buttons in different places. In this case, a browser action **and** a page action [2], which would be a button inside the address bar. Having two different buttons in two different places would not be that intuitive for users though... Also, there are thoughts about using page actions to support android versions of Firefox (see #1 ). Any ideas or comments on this?

Another question I have is: Do you have any problems using the current `Alt+shift+X` hotkey to toggle the configurations?

[1] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Browser_action
[2] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction

**Comment by cb88** [comment]
No `ALT+shift+X` works but is a bit awkward I suppose it depends on if your usage is keyboard centric or mouse centric (I'm mouse centric as I tend to be using KiCad etc...).

I suppose it might be possible to solve this with a separate extension that only enables / disables the proxy on button click. I don't really like the buttons inside the address bar honestly as it already seems cluttered with the ones mozilla has dumped in there.

**Comment by athos-ribeiro** [comment]
What about the initial though of having an options page where you could permanently change noturno behaviour to act as single click toggle?

Would that be better or worse than what we have today? In this case you would have to open the addons menu to change the proxy host or port. I believe we could implement that quite fast for a next version :)

**Comment by cb88** [comment]
That would be fine too I suppose.

**Comment by sorrodp** [comment]
I support having exclusively the on/off function when left-clicking on the toolbar icon, and then some other means (right-click, or going through the add-ons menu) to access the configuration of noturno.

Thanks,

**Comment by athos-ribeiro** [comment]
We added a menu option, which can be accesses with a right click in the addon button. By checkint the "one click toggle" box, the configuration menu will not be accessed with a single click anymore: instead, you can toggle the proxy configurations on/off

**Comment by athos-ribeiro** [comment]
Feedback would be nice before we release this new feature in the next version.

**Comment by cb88** [comment]
I just updated to 1.2 looks like it works as expected DNS queries also seem to be redirected correctly.

**Comment by athos-ribeiro** [comment]
Thanks for the feedback :)
