### ISSUE TITLE
DNS leaked with socks5 

### ISSUE THREAD

**Issue by cb88** [athos-ribeiro/noturno#13]
In the manual settings preferences of Firefox there is a checkbox to proxy DNS queries which works.

However, noturno does not proxy DNS queries or allow enabling it with socks5...

**Comment by athos-ribeiro** [comment]
Nice catch!

I will take a look into adding an option for that (maybe a checkbox as well) to do the same.

**Comment by athos-ribeiro** [comment]
The issue goes up to the firefox implementation of the PAC file. Although not yet documented, there is support for returning JS objects from the FindProxyForURL function, as pointed out in [1]. 

The format of the object is as follows (copied from the bug in [1]):

```
|type| -- string, one of "http"|"https|"socks5"|"socks4"|"socks"|"direct"|"ignore"|. note that "socks" is a synonym for socks5. "ignore" means Firefox should handle this URI through its global proxy settings (which could be wpad, pac, system, direct/none, or a proxy server) or other installed addons.
|host| -- string
|port| -- integer between 1 and 65536 (TCP/IP does not allow for ports outside that range)
|username| -- optional string
|password| -- optional string
|proxyDNS| -- optional boolean. default false. if true, TRANSPARENT_PROXY_RESOLVES_HOST is set as a flag on nsIProxyInfo.flags so that the proxy server is used to resolve certain DNS queries.
|failoverTimeout| -- optional integer. default 1. Number of seconds before timing out and trying the next proxy in the failover array
|failover| -- optional array of objects with these same properties. null to terminate. default null (no failover, which is the desired case 99% of the time in my experience).

example:

{
type: "socks",
host: "foo.com",
port: 1080,
proxyDNS: true,
failoverTimeout: 1,
failover: {
  type: "socks",
  host: "bar.com",
  port: 1080,
  proxyDNS: true,
  failoverTimeout: 0,
  failover: null
}
}
```

Which means that we can also support authentication directly in noturno.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1381290

**Comment by athos-ribeiro** [comment]
b8a27e4 fixes this issue. It would be nice to get some feedback here before releasing a new version with this fix.

**Comment by cb88** [comment]
As far as I can tell it isn't leaking with 1.2 that Firefox automatically updated to recently.
